In [ ]:
# df[df['col'] > value]

In [1]:
import pandas as pd

In [2]:
data = {
    'age': [25, 35, 40, 28],
    'city': ['NYC', 'LA', 'NYC', 'SF'],
    'salary': [50000, 70000, 80000, 45000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df[df['age']>30]

   age city  salary
1   35   LA   70000
2   40  NYC   80000

In [7]:
df[(df['age']>30) &(df['city']=='NYC')]
# Always use () with &

   age city  salary
2   40  NYC   80000

In [8]:
df[(df['city']=="NYC") | df['city']=="LA"]

Empty DataFrame
Columns: [age, city, salary]
Index: []

In [9]:
df[df['city'].isin(['NYC','LA'])]

   age city  salary
0   25  NYC   50000
1   35   LA   70000
2   40  NYC   80000

In [10]:
df[df['age'].between(30,40)]

   age city  salary
1   35   LA   70000
2   40  NYC   80000