In [1]:
import pandas as pd

data = {
    'city': ['NYC', 'LA', 'NYC', 'LA', 'SF'],
    'sales': [100, 200, 150, 250, 300],
    'age': [25, 30, 35, 40, 28]
}

df = pd.DataFrame(data)

print(df)

  city  sales  age
0  NYC    100   25
1   LA    200   30
2  NYC    150   35
3   LA    250   40
4   SF    300   28

In [2]:
df.groupby('city')['sales'].sum()

city
LA     450
NYC    250
SF     300
Name: sales, dtype: int64

In [3]:
df.groupby('city').size()

city
LA     2
NYC    2
SF     1
dtype: int64

In [4]:
df.groupby('city').agg({'sales':'sum','age':'mean'})

      sales   age
city
LA      450  35.0
NYC     250  30.0
SF      300  28.0

In [5]:
df.groupby('city')['age'].mean()

city
LA     35.0
NYC    30.0
SF     28.0
Name: age, dtype: float64

In [6]:
df.groupby('city')['sales'].sum().reset_index()

  city  sales
0   LA    450
1  NYC    250
2   SF    300

In [7]:
df.groupby('city')['sales'].sum().sort_values(ascending=False)

city
LA     450
SF     300
NYC    250
Name: sales, dtype: int64