In [1]:
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'id': [2, 3, 4],
    'salary': [50000, 60000, 70000]
})

In [3]:
df=pd.merge(df1,df2,on='id',how='inner')
df

   id     name  salary
0   2      Bob   50000
1   3  Charlie   60000

In [5]:
df=pd.merge(df1,df2,on='id',how='left')
df

   id     name   salary
0   1    Alice      NaN
1   2      Bob  50000.0
2   3  Charlie  60000.0

In [11]:
df=pd.merge(df1,df2,on='id',how='outer')
df.reset_index(drop=True)

   id     name   salary
0   1    Alice      NaN
1   2      Bob  50000.0
2   3  Charlie  60000.0
3   4      NaN  70000.0