In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("file.csv")

In [9]:
df

,customer_id,first_name,last_name,age,gender,city,salary,signup_date,last_login,purchases,target
0,1,John,Doe,28.0,Male,Bangalore,50000.0,2021-01-15,2023-06-01,5,1
1,2,Jane,Smith,34.0,Female,Mumbai,60000.0,2020-11-20,2023-05-25,8,0
2,3,Sam,Brown,NaN,Male,Delhi,45000.0,2022-03-10,2023-06-10,2,1
3,4,Emily,Davis,45.0,Female,Chennai,NaN,2019-07-30,2023-04-15,10,0
4,5,Michael,Wilson,23.0,Male,Bangalore,30000.0,2021-08-05,2023-06-20,1,1
5,6,Sarah,Moore,31.0,Female,Hyderabad,52000.0,2020-09-12,2023-05-30,6,0
6,7,David,Taylor,38.0,Male,Pune,58000.0,2018-12-01,2023-03-10,7,1
7,8,Linda,Anderson,29.0,Female,Delhi,49000.0,2022-01-22,2023-06-18,3,0
8,9,James,Thomas,41.0,Male,Mumbai,62000.0,2019-05-17,2023-04-22,9,1
9,10,Patricia,Jackson,36.0,Female,Chennai,57000.0,2021-03-03,2023-05-12,4,0
10,11,Robert,White,27.0,Male,Bangalore,48000.0,2022-07-19,2023-06-21,2,1
11,12,Jennifer,Harris,33.0,Female,Pune,55000.0,2020-06-25,2023-05-28,5,0
12,13,William,Martin,39.0,Male,Hyderabad,61000.0,2019-10-10,2023-04-05,8,1
13,14,Elizabeth,Thompson,26.0,Female,Delhi,47000.0,2021-12-14,2023-06-19,3,0
14,15,Charles,Garcia,44.0,Male,Mumbai,63000.0,2018-11-11,2023-03-28,9,1
15,16,Barbara,Martinez,30.0,Female,Bangalore,51000.0,2022-02-08,2023-06-17,4,0
16,17,Joseph,Robinson,37.0,Male,Pune,59000.0,2020-04-21,2023-05-10,6,1
17,18,Susan,Clark,32.0,Female,Chennai,53000.0,2021-06-30,2023-06-11,5,0
18,19,Thomas,Rodriguez,40.0,Male,Hyderabad,62000.0,2019-09-09,2023-04-18,7,1
19,20,Karen,Lewis,35.0,Female,Delhi,56000.0,2020-01-01,2023-05-22,6,0

In [10]:
#inspect 
df.head()

,customer_id,first_name,last_name,age,gender,city,salary,signup_date,last_login,purchases,target
0,1,John,Doe,28.0,Male,Bangalore,50000.0,2021-01-15,2023-06-01,5,1
1,2,Jane,Smith,34.0,Female,Mumbai,60000.0,2020-11-20,2023-05-25,8,0
2,3,Sam,Brown,NaN,Male,Delhi,45000.0,2022-03-10,2023-06-10,2,1
3,4,Emily,Davis,45.0,Female,Chennai,NaN,2019-07-30,2023-04-15,10,0
4,5,Michael,Wilson,23.0,Male,Bangalore,30000.0,2021-08-05,2023-06-20,1,1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  20 non-null     int64
 1   first_name   20 non-null     object
 2   last_name    20 non-null     object
 3   age          19 non-null     float64
 4   gender       20 non-null     object
 5   city         20 non-null     object
 6   salary       19 non-null     float64
 7   signup_date  20 non-null     object
 8   last_login   20 non-null     object
 9   purchases    20 non-null     int64
 10  target       20 non-null     int64
dtypes: float64(2), int64(3), object(6)
memory usage: 1.8+ KB

In [12]:
df.describe()

       customer_id        age        salary  purchases     target
count     20.00000  19.000000     19.000000  20.000000  20.000000
mean      10.50000  34.105263  53578.947368   5.500000   0.500000
std        5.91608   6.172472   7967.404355   2.564946   0.512989
min        1.00000  23.000000  30000.000000   1.000000   0.000000
25%        5.75000  29.500000  49500.000000   3.750000   0.000000
50%       10.50000  34.000000  55000.000000   5.500000   0.500000
75%       15.25000  38.500000  59500.000000   7.250000   1.000000
max       20.00000  45.000000  63000.000000  10.000000   1.000000

In [15]:
#select
print(df['age'])

0     28.0
1     34.0
2      NaN
3     45.0
4     23.0
5     31.0
6     38.0
7     29.0
8     41.0
9     36.0
10    27.0
11    33.0
12    39.0
13    26.0
14    44.0
15    30.0
16    37.0
17    32.0
18    40.0
19    35.0
Name: age, dtype: float64

In [17]:
print(df.loc[0])

customer_id             1
first_name           John
last_name             Doe
age                  28.0
gender               Male
city            Bangalore
salary            50000.0
signup_date    2021-01-15
last_login     2023-06-01
purchases               5
target                  1
Name: 0, dtype: object

In [18]:
print(df.iloc[0])

customer_id             1
first_name           John
last_name             Doe
age                  28.0
gender               Male
city            Bangalore
salary            50000.0
signup_date    2021-01-15
last_login     2023-06-01
purchases               5
target                  1
Name: 0, dtype: object

In [19]:
#filter
print(df[df['purchases']>5])

    customer_id first_name  last_name   age  gender       city   salary  \
1             2       Jane      Smith  34.0  Female     Mumbai  60000.0
3             4      Emily      Davis  45.0  Female    Chennai      NaN
5             6      Sarah      Moore  31.0  Female  Hyderabad  52000.0
6             7      David     Taylor  38.0    Male       Pune  58000.0
8             9      James     Thomas  41.0    Male     Mumbai  62000.0
12           13    William     Martin  39.0    Male  Hyderabad  61000.0
14           15    Charles     Garcia  44.0    Male     Mumbai  63000.0
16           17     Joseph   Robinson  37.0    Male       Pune  59000.0
18           19     Thomas  Rodriguez  40.0    Male  Hyderabad  62000.0
19           20      Karen      Lewis  35.0  Female      Delhi  56000.0

   signup_date  last_login  purchases  target
1   2020-11-20  2023-05-25          8       0
3   2019-07-30  2023-04-15         10       0
5   2020-09-12  2023-05-30          6       0
6   2018-12-01  2023-03-10          7       1
8   2019-05-17  2023-04-22          9       1
12  2019-10-10  2023-04-05          8       1
14  2018-11-11  2023-03-28          9       1
16  2020-04-21  2023-05-10          6       1
18  2019-09-09  2023-04-18          7       1
19  2020-01-01  2023-05-22          6       0

In [22]:
#clean
print(df.isna().sum())
df=df.fillna({
    'age':df['age'].mean(),
    'salary':df['salary'].mean()
})
print(df)

customer_id    0
first_name     0
last_name      0
age            0
gender         0
city           0
salary         0
signup_date    0
last_login     0
purchases      0
target         0
dtype: int64
    customer_id first_name  last_name        age  gender       city  \
0             1       John        Doe  28.000000    Male  Bangalore
1             2       Jane      Smith  34.000000  Female     Mumbai
2             3        Sam      Brown  34.105263    Male      Delhi
3             4      Emily      Davis  45.000000  Female    Chennai
4             5    Michael     Wilson  23.000000    Male  Bangalore
5             6      Sarah      Moore  31.000000  Female  Hyderabad
6             7      David     Taylor  38.000000    Male       Pune
7             8      Linda   Anderson  29.000000  Female      Delhi
8             9      James     Thomas  41.000000    Male     Mumbai
9            10   Patricia    Jackson  36.000000  Female    Chennai
10           11     Robert      White  27.000000    Male  Bangalore
11           12   Jennifer     Harris  33.000000  Female       Pune
12           13    William     Martin  39.000000    Male  Hyderabad
13           14  Elizabeth   Thompson  26.000000  Female      Delhi
14           15    Charles     Garcia  44.000000    Male     Mumbai
15           16    Barbara   Martinez  30.000000  Female  Bangalore
16           17     Joseph   Robinson  37.000000    Male       Pune
17           18      Susan      Clark  32.000000  Female    Chennai
18           19     Thomas  Rodriguez  40.000000    Male  Hyderabad
19           20      Karen      Lewis  35.000000  Female      Delhi

          salary signup_date  last_login  purchases  target
0   50000.000000  2021-01-15  2023-06-01          5       1
1   60000.000000  2020-11-20  2023-05-25          8       0
2   45000.000000  2022-03-10  2023-06-10          2       1
3   53578.947368  2019-07-30  2023-04-15         10       0
4   30000.000000  2021-08-05  2023-06-20          1       1
5   52000.000000  2020-09-12  2023-05-30          6       0
6   58000.000000  2018-12-01  2023-03-10          7       1
7   49000.000000  2022-01-22  2023-06-18          3       0
8   62000.000000  2019-05-17  2023-04-22          9       1
9   57000.000000  2021-03-03  2023-05-12          4       0
10  48000.000000  2022-07-19  2023-06-21          2       1
11  55000.000000  2020-06-25  2023-05-28          5       0
12  61000.000000  2019-10-10  2023-04-05          8       1
13  47000.000000  2021-12-14  2023-06-19          3       0
14  63000.000000  2018-11-11  2023-03-28          9       1
15  51000.000000  2022-02-08  2023-06-17          4       0
16  59000.000000  2020-04-21  2023-05-10          6       1
17  53000.000000  2021-06-30  2023-06-11          5       0
18  62000.000000  2019-09-09  2023-04-18          7       1
19  56000.000000  2020-01-01  2023-05-22          6       0

In [23]:
df=df.dropna()

In [24]:
# New column: total value indicator
df['salary_per_purchase'] = df['salary'] / (df['purchases'] + 1)

# Apply
df['age_doubled'] = df['age'].apply(lambda x: x * 2)

In [25]:
# Avg salary & total purchases per city
grouped = df.groupby('city').agg({
    'salary': 'mean',
    'purchases': 'sum'
})

print(grouped)

                 salary  purchases
city
Bangalore  44750.000000         12
Chennai    54526.315789         19
Delhi      49250.000000         14
Hyderabad  58333.333333         21
Mumbai     61666.666667         26
Pune       57333.333333         18

In [26]:
# =========================
# 🔗 MERGE (EXAMPLE)
# =========================

# Create dummy second dataframe
df2 = df[['customer_id', 'target']]

merged = pd.merge(df, df2, on='customer_id', how='left')
print(merged.head())

   customer_id first_name last_name        age  gender       city  \
0            1       John       Doe  28.000000    Male  Bangalore
1            2       Jane     Smith  34.000000  Female     Mumbai
2            3        Sam     Brown  34.105263    Male      Delhi
3            4      Emily     Davis  45.000000  Female    Chennai
4            5    Michael    Wilson  23.000000    Male  Bangalore

         salary signup_date  last_login  purchases  target_x  \
0  50000.000000  2021-01-15  2023-06-01          5         1
1  60000.000000  2020-11-20  2023-05-25          8         0
2  45000.000000  2022-03-10  2023-06-10          2         1
3  53578.947368  2019-07-30  2023-04-15         10         0
4  30000.000000  2021-08-05  2023-06-20          1         1

   salary_per_purchase  age_doubled  target_y
0          8333.333333    56.000000         1
1          6666.666667    68.000000         0
2         15000.000000    68.210526         1
3          4870.813397    90.000000         0
4         15000.000000    46.000000         1

In [27]:
# =========================
# 🔄 PIVOT
# =========================

pivot = pd.pivot_table(
    df,
    values='salary',
    index='city',
    columns='gender',
    aggfunc='mean'
)

print(pivot)

gender           Female          Male
city
Bangalore  51000.000000  42666.666667
Chennai    54526.315789           NaN
Delhi      50666.666667  45000.000000
Hyderabad  52000.000000  61500.000000
Mumbai     60000.000000  62500.000000
Pune       55000.000000  58500.000000

In [28]:

# =========================
# 📊 SORTING
# =========================

sorted_df = df.sort_values(by='salary', ascending=False)
print(sorted_df.head())

    customer_id first_name  last_name   age  gender       city   salary  \
14           15    Charles     Garcia  44.0    Male     Mumbai  63000.0
18           19     Thomas  Rodriguez  40.0    Male  Hyderabad  62000.0
8             9      James     Thomas  41.0    Male     Mumbai  62000.0
12           13    William     Martin  39.0    Male  Hyderabad  61000.0
1             2       Jane      Smith  34.0  Female     Mumbai  60000.0

   signup_date  last_login  purchases  target  salary_per_purchase  \
14  2018-11-11  2023-03-28          9       1          6300.000000
18  2019-09-09  2023-04-18          7       1          7750.000000
8   2019-05-17  2023-04-22          9       1          6200.000000
12  2019-10-10  2023-04-05          8       1          6777.777778
1   2020-11-20  2023-05-25          8       0          6666.666667

    age_doubled
14         88.0
18         80.0
8          82.0
12         78.0
1          68.0

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# =========================
# 📥 LOAD DATA
# =========================
df = pd.read_csv("file.csv")

# =========================
# 🧹 DATA CLEANING
# =========================

# Convert date columns
df['signup_date'] = pd.to_datetime(df['signup_date'])
df['last_login'] = pd.to_datetime(df['last_login'])

# Create new feature (VERY IMPORTANT)
df['days_active'] = (df['last_login'] - df['signup_date']).dt.days

# Drop original date columns
df = df.drop(columns=['signup_date', 'last_login'])

# Drop unnecessary text columns
df = df.drop(columns=['first_name', 'last_name'])

# Handle missing values (before encoding is okay too)
df['age'] = df['age'].fillna(df['age'].mean())
df['salary'] = df['salary'].fillna(df['salary'].mean())

# Encode categorical variables
df = pd.get_dummies(df, columns=['gender', 'city'], drop_first=True)

# =========================
# 🎯 FEATURES & TARGET
# =========================
X = df.drop('target', axis=1)
y = df['target']

# 🚨 SAFETY LINE (prevents dtype errors)
X = X.select_dtypes(include=['number'])

# =========================
# ✂️ TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================
# 🧩 HANDLE MISSING VALUES
# =========================
imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# =========================
# 📏 FEATURE SCALING
# =========================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =========================
# 🤖 MODEL TRAINING
# =========================
model = LogisticRegression()
model.fit(X_train, y_train)

# =========================
# 🔮 PREDICTION
# =========================
y_pred = model.predict(X_test)

# =========================
# 📊 EVALUATION
# =========================
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.75