In [1]:
import pandas as pd

data = {
    'city': ['NYC', 'NYC', 'LA', 'LA'],
    'month': ['Jan', 'Feb', 'Jan', 'Feb'],
    'sales': [100, 150, 200, 250]
}

df = pd.DataFrame(data)

print(df)

  city month  sales
0  NYC   Jan    100
1  NYC   Feb    150
2   LA   Jan    200
3   LA   Feb    250

In [3]:
df_pivot=df.pivot_table(
    values="sales",
    index='city',
    columns='month',
    aggfunc='sum'
)
df_pivot=df_pivot.reset_index()
df_pivot

month city  Feb  Jan
0       LA  250  200
1      NYC  150  100

In [5]:
df2 = pd.DataFrame({
    'id': [1, 2],
    'col1': [10, 20],
    'col2': [30, 40]
})

In [7]:
df_melt=pd.melt(df2,id_vars=['id'],value_vars=['col1','col2'])
df_melt

   id variable  value
0   1     col1     10
1   2     col1     20
2   1     col2     30
3   2     col2     40