In [6]:
import pandas as pd

data = {
    'name': ['A', 'B', 'C', 'D', 'E'],
    'sales': [500, 700, 300, 900, 600],
    'city':['NYC','Germany','ABC','DEF','GHI']
}

df = pd.DataFrame(data)

print(df)

  name  sales     city
0    A    500      NYC
1    B    700  Germany
2    C    300      ABC
3    D    900      DEF
4    E    600      GHI

In [7]:
df.sort_values('sales',ascending=False)

  name  sales     city
3    D    900      DEF
1    B    700  Germany
4    E    600      GHI
0    A    500      NYC
2    C    300      ABC

In [8]:
df.nlargest(3,'sales')

  name  sales     city
3    D    900      DEF
1    B    700  Germany
4    E    600      GHI

In [9]:
df.nsmallest(2,'sales')

  name  sales city
2    C    300  ABC
0    A    500  NYC

In [10]:
df.sort_values(['city','sales'],ascending=[True,False])

  name  sales     city
2    C    300      ABC
3    D    900      DEF
4    E    600      GHI
1    B    700  Germany
0    A    500      NYC

In [15]:
df['rank']=df['sales'].rank(ascending=False)

In [16]:
df.sort_values('sales',ascending=False).reset_index(drop=True)

  name  sales     city  rank
0    D    900      DEF   1.0
1    B    700  Germany   2.0
2    E    600      GHI   3.0
3    A    500      NYC   4.0
4    C    300      ABC   5.0